language: python
cache: pip
services: mongodb
sudo: required
python:
  - "3.6"
install:
  - ./install-mpi.sh openmpi
  - pip install -r requirements.txt
  - pip install -r requirements-optional.txt
before_script:
  - python setup.py develop
  - cd $HOME
  - curl -O https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.6.5.tgz
  - tar -zxvf mongodb-linux-x86_64-3.6.5.tgz
  - mkdir -p mongodbdata
  - touch mongodblog
  - |
    mongodb-linux-x86_64-3.6.5/bin/mongod \
    --port 27020 --dbpath mongodbdata --logpath mongodblog \
    --auth --bind_ip_all --fork
  - |
     mongodb-linux-x86_64-3.6.5/bin/mongo 127.0.0.1:27020/admin --eval \
     'db.createUser({user:"mongoadmin",pwd:"mongoadminpass",roles:["root"]});'
  - cd -
script:
  - nosetests -v maggma
  - mpiexec -n 2  python $PWD/maggma/tests/mpi_test.py
notifications:
  email:
    recipients:
      - montoyjh@lbl.gov
      - shyamd@lbl.gov
      - dwinston@lbl.gov
    on_success: change
    on_failure: always
deploy:
  provider: pypi
  user: dwinston
  distributions: sdist bdist_wheel
  password:
    secure: QWANYNRV95wP9XlG88Z4NV9cepgUOlt6+caRNEiRZYACYTMvSzNH8uTblVciqbWr2idmDSayzGKkUNh+GqrpgC0GjioIpeazt8BBr+PUF/D49ljXapJo7jEjpU72rKRJ6bvO+ifJKV6xHX60gDctB2wJAovqx+LJEpT7Lj14RutUqkfqmQZTr0H6QoPpH9F1y9HKyPdA7VfyJwwulBdG79uW6GzeI6lEqWyEQmTAPga/jDgY3P0+mLVVa7Dc4Qr/R80eM5HFGc25K1yz2WUOnFDZebJ/y9p82pfEdUVDzAphdfh7eFnE6S+PRQ3GkAmb9D9+bv1HMxBv7UEZohvos36+UDTGcIoCxDc0FxlvmSH7OiNNH9Xo4Nv5glpy9RnKFASfzyRcUcyGIUB/R8ctTM0lBJxdV3ik2OxgK9aOeKjPeUqCS0HxTdthY0ZyjZwDsshFzYU7Wf0wgXIWeRLb+Q2VxU9hhja1NITFlHrot7SmPXXsr7bxtHUeurtM1naBfMar7jK20aCPiDdqYy88N4v4OdMHNVnjHQUdrn2rvetCtkMJUIoCQRlgI8z3amG+1xK4CX9fVdwMaS434J2dZXSUuJSyAxrhva5ASzBboOdXMpx+u4Dq7R2vhYyqGKBJ5HLVKHLpxHxZpXn2bbverR1eEn+oe7trpasqS+xXJ2E=
  on:
    tags: true
